[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-cors = "0.7.1"
actix-web = "4.10.2"
dotenvy = "0.15.7"
lettre = { version = "0.11.15", features = ["smtp-transport", "builder"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
